export const debateTopics = [
  "Social media platforms should ban political content.",
  "Cancel culture is necessary for accountability.",
  "Freedom of speech should have strict limits.",
  "AI-generated content is killing creativity.",
  "Surveillance is more important than privacy in today's world.",
  "AI will take over human jobs.",
  "Companies should be allowed to collect user data in exchange for free services.",
  "Cryptocurrency is a scam, not the future of finance.",
  "Employees should work only four days a week for better productivity.",
  "Traditional Jobs will die due to AI.",
  "Multitasking boosts productivity.",
  "Failure teaches more valuable lessons than success.",
  "Discipline is more important than motivation for success.",
  "Schools should prioritize practical skills over theoretical knowledge.",
  "Socializing is more valuable than self-improvement.",
  "Voting should be mandatory for all eligible citizens.",
  "Universal basic income is a necessary economic policy.",
  "Governments must regulate fake news on the internet.",
  "Wealthy nations have a moral responsibility to help poorer countries.",
  "Social media activism creates real and meaningful change.",
  "Free will is just an illusion.",
  "Humans are naturally selfish, not inherently good.",
  "Happiness should be the ultimate goal of life.",
  "Money can buy happiness.",
  "Success depends more on luck than hard work.",
];
